# Generated by Django 4.2.1 on 2025-07-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Permisos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("acceso_admin_panel", "Puede acceder al panel de administración"),
                    (
                        "acceso_solo_Usuarios",
                        "Puede acceder a informacion de solo Usurios",
                    ),
                ],
            },
        ),
    ]
