# Generated by Django 5.2.1 on 2025-06-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DummyModel',
            new_name='Permisos',
        ),
        migrations.AlterModelOptions(
            name='permisos',
            options={'permissions': [('acceso_admin_panel', 'Puede acceder al panel de administración'), ('acceso_solo_Usuarios', 'Puede acceder a informacion de solo Usurios')]},
        ),
    ]
